### ISSUE TITLE
Can't give color property to be non numerical like 'none' or 'white'

### ISSUE THREAD

**Issue by ahmadalibaloch** [juliangarnier/anime#154]
I am simply trying to set background property of a dive to be 'none' but it gives error: I think it only accepts rgb in the format "#xxx", any workaround?
`angular.min.js:108 TypeError: Cannot read property 'end' of undefined
    at createAnimation (http://localhost:52035/Scripts/anime.js:581:50)
    at properties.map.prop (http://localhost:52035/Scripts/anime.js:590:16)
    at Array.map (native)
    at animatables.map.animatable (http://localhost:52035/Scripts/anime.js:589:25)
    at Array.map (native)
    at getAnimations (http://localhost:52035/Scripts/anime.js:588:37)
    at createNewInstance (http://localhost:52035/Scripts/anime.js:607:24)
    at anime (http://localhost:52035/Scripts/anime.js:656:20)`

**Comment by juliangarnier** [comment]
Yep, `none` is not a color, what is a transition between red and nothing should looks like?
I don't see any workaround to this issues since RGBA is not supported by anime.
Or try animating the `opacity` instead.
