### ISSUE TITLE
Map is not defined

### ISSUE THREAD

**Issue by zoharit** [juliangarnier/anime#614]
Sometimes, we are getting the following error, while using anime.js. it is bundled inside browserify, hence the bundle reference.
We are not sure how to reproduce, or how to get into this error, but we keep on getting this:

ReferenceError: Map is not defined
  at getElementTransforms(/bundle.js:1:437032)
  at ? (/bundle.js:1:439931)
  at Array.map(/Cat/76)
  at getAnimatables(/bundle.js:1:439860)
  at ? (/bundle.js:1:443734)
  at anime(/bundle.js:1:443956)
  at Object.t.add(/bundle.js:1:449041)
  at Nanocomponent._$circle_171.load(/bundle.js:1:462466)
  at Nanocomponent.(anonymous function) [as _load](/bundle.js:1:456703)
  at ? (/bundle.js:1:452651)
  at o(/bundle.js:1:66264)

**Comment by kn0wn** [comment]
Hi @zoharit are you still encountering this issue?
